apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: birdnet-go-data
  namespace: applications
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: zfs-iscsi
