apiVersion: v1
kind: Service
metadata:
  name: clusterfuck-default-backend
  namespace: ingress
spec:
  ports:
    - name: "https"
      protocol: TCP
      port: 443
      targetPort: 443
---
kind: Endpoints
apiVersion: v1
metadata:
  name: clusterfuck-default-backend
  namespace: ingress
subsets:
  - addresses:
      - ip: 10.0.10.100
    ports:
      - port: 443