apiVersion: v1
kind: ConfigMap
metadata:
  name: kiosk-config
  namespace: immich
data:
  config.yaml: |
    immich_url: "https://photos.bo0tzz.me"

    disable_screensaver: true
    
    kiosk:
      behind_proxy: true
